# Generated by Django 6.1 on 2026-10-07 02:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('description', models.TextField(verbose_name='Общее описание')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters', verbose_name='Постер')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
            },
        ),
        migrations.CreateModel(
            name='GameSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price_per_hour', models.IntegerField(verbose_name='Цена в рублях за час')),
            ],
            options={
                'verbose_name': 'Игровой набор',
                'verbose_name_plural': 'Игровые наборы',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('description', models.TextField(verbose_name='Общее описание')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Наименование')),
                ('description', models.TextField(verbose_name='Описание')),
                ('capacity', models.IntegerField(verbose_name='Вместимость человек')),
                ('price_per_hour', models.IntegerField(verbose_name='Цена за 1 час брони на 1 человека')),
            ],
            options={
                'verbose_name': 'Зал',
                'verbose_name_plural': 'Залы',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.IntegerField(default=0, verbose_name='Общая стоимость заказа')),
                ('status', models.TextField(choices=[('в работе', 'В работе'), ('завершен', 'Завершен'), ('отменён', 'Отменён')], default='в работе', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='GameOnSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='VRclub.game')),
                ('id_game_set', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='VRclub.gameset')),
            ],
            options={
                'verbose_name': 'Игра на игровом наборе',
                'verbose_name_plural': 'Игры на игровых наборах',
            },
        ),
        migrations.CreateModel(
            name='GenreInGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='VRclub.game')),
                ('id_genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='VRclub.genre')),
            ],
            options={
                'verbose_name': 'Жанр в игре',
                'verbose_name_plural': 'Жанры в играх',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Время начала')),
                ('end_time', models.DateTimeField(verbose_name='Время конца')),
                ('game_set_price', models.IntegerField(verbose_name='Цена в рублях за час')),
                ('hall_price', models.IntegerField(verbose_name='Цена за 1 час брони на 1 человека')),
                ('id_game_set', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='VRclub.gameset')),
                ('id_hall', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='VRclub.hall')),
                ('id_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='VRclub.order')),
            ],
            options={
                'verbose_name': 'Позиция',
                'verbose_name_plural': 'Позиции',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(0, 'Undefined'), (1, 'Employee'), (2, 'Client')], default=0, verbose_name='Роль')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
